// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTests.Features.Event_Engine
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Presence Event Engine")]
    [NUnit.Framework.CategoryAttribute("featureSet=presenceEventEngine")]
    [NUnit.Framework.CategoryAttribute("beta")]
    public partial class PresenceEventEngineFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "featureSet=presenceEventEngine",
                "beta"};
        
#line 1 "presence-engine.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/event-engine", "Presence Event Engine", "  Validating the correctness of EE for Presence events", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
  #line hidden
#line 6
    await testRunner.GivenAsync("the demo keyset with Presence EE enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfully joined a few channels")]
        [NUnit.Framework.CategoryAttribute("contract=presenceTestMultipleWait")]
        public async System.Threading.Tasks.Task SuccessfullyJoinedAFewChannels()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=presenceTestMultipleWait"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully joined a few channels", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 10
    await testRunner.GivenAsync("heartbeatInterval set to \'1\', timeout set to \'60\' and suppressLeaveEvents set to " +
                        "\'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
    await testRunner.WhenAsync("I join \'first\', \'second\', \'third\' channels", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("I wait \'3\' seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "name"});
                table7.AddRow(new string[] {
                            "event",
                            "JOINED"});
                table7.AddRow(new string[] {
                            "invocation",
                            "HEARTBEAT"});
                table7.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_SUCCESS"});
                table7.AddRow(new string[] {
                            "invocation",
                            "WAIT"});
                table7.AddRow(new string[] {
                            "event",
                            "TIMES_UP"});
                table7.AddRow(new string[] {
                            "invocation",
                            "CANCEL_WAIT"});
                table7.AddRow(new string[] {
                            "invocation",
                            "HEARTBEAT"});
                table7.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_SUCCESS"});
                table7.AddRow(new string[] {
                            "invocation",
                            "WAIT"});
                table7.AddRow(new string[] {
                            "event",
                            "TIMES_UP"});
                table7.AddRow(new string[] {
                            "invocation",
                            "CANCEL_WAIT"});
                table7.AddRow(new string[] {
                            "invocation",
                            "HEARTBEAT"});
#line 13
    await testRunner.AndAsync("I observe the following Events and Invocations of the Presence EE:", ((string)(null)), table7, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfully joined a few channels with presence")]
        [NUnit.Framework.CategoryAttribute("contract=presenceJoin")]
        public async System.Threading.Tasks.Task SuccessfullyJoinedAFewChannelsWithPresence()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=presenceJoin"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully joined a few channels with presence", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("heartbeatInterval set to \'1\', timeout set to \'60\' and suppressLeaveEvents set to " +
                        "\'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync("I join \'first\', \'second\', \'third\' channels with presence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("I wait for getting Presence joined events", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "name"});
                table8.AddRow(new string[] {
                            "event",
                            "JOINED"});
                table8.AddRow(new string[] {
                            "invocation",
                            "HEARTBEAT"});
                table8.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_SUCCESS"});
                table8.AddRow(new string[] {
                            "invocation",
                            "WAIT"});
#line 33
    await testRunner.AndAsync("I observe the following Events and Invocations of the Presence EE:", ((string)(null)), table8, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Recovery from one unexpected error along the way")]
        [NUnit.Framework.CategoryAttribute("contract=presenceJoinWithAnError")]
        public async System.Threading.Tasks.Task RecoveryFromOneUnexpectedErrorAlongTheWay()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=presenceJoinWithAnError"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recovery from one unexpected error along the way", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 42
    await testRunner.GivenAsync("heartbeatInterval set to \'1\', timeout set to \'60\' and suppressLeaveEvents set to " +
                        "\'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
    await testRunner.GivenAsync("a linear reconnection policy with 3 retries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 44
    await testRunner.WhenAsync("I join \'first\', \'second\', \'third\' channels with presence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("I wait for getting Presence joined events", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "name"});
                table9.AddRow(new string[] {
                            "event",
                            "JOINED"});
                table9.AddRow(new string[] {
                            "invocation",
                            "HEARTBEAT"});
                table9.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_FAILURE"});
                table9.AddRow(new string[] {
                            "invocation",
                            "DELAYED_HEARTBEAT"});
                table9.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_SUCCESS"});
                table9.AddRow(new string[] {
                            "invocation",
                            "CANCEL_DELAYED_HEARTBEAT"});
                table9.AddRow(new string[] {
                            "invocation",
                            "WAIT"});
#line 46
    await testRunner.AndAsync("I observe the following Events and Invocations of the Presence EE:", ((string)(null)), table9, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Complete handshake failure")]
        [NUnit.Framework.CategoryAttribute("contract=presenceJoinWithContinuousFailures")]
        public async System.Threading.Tasks.Task CompleteHandshakeFailure()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=presenceJoinWithContinuousFailures"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Complete handshake failure", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 58
    await testRunner.GivenAsync("heartbeatInterval set to \'1\', timeout set to \'60\' and suppressLeaveEvents set to " +
                        "\'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 59
    await testRunner.GivenAsync("a linear reconnection policy with 3 retries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 60
    await testRunner.WhenAsync("I join \'first\', \'second\', \'third\' channels", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 61
    await testRunner.ThenAsync("I receive an error in my heartbeat response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "name"});
                table10.AddRow(new string[] {
                            "event",
                            "JOINED"});
                table10.AddRow(new string[] {
                            "invocation",
                            "HEARTBEAT"});
                table10.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_FAILURE"});
                table10.AddRow(new string[] {
                            "invocation",
                            "DELAYED_HEARTBEAT"});
                table10.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_FAILURE"});
                table10.AddRow(new string[] {
                            "invocation",
                            "CANCEL_DELAYED_HEARTBEAT"});
                table10.AddRow(new string[] {
                            "invocation",
                            "DELAYED_HEARTBEAT"});
                table10.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_FAILURE"});
                table10.AddRow(new string[] {
                            "invocation",
                            "CANCEL_DELAYED_HEARTBEAT"});
                table10.AddRow(new string[] {
                            "invocation",
                            "DELAYED_HEARTBEAT"});
                table10.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_FAILURE"});
                table10.AddRow(new string[] {
                            "invocation",
                            "CANCEL_DELAYED_HEARTBEAT"});
                table10.AddRow(new string[] {
                            "invocation",
                            "DELAYED_HEARTBEAT"});
                table10.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_GIVEUP"});
                table10.AddRow(new string[] {
                            "invocation",
                            "CANCEL_DELAYED_HEARTBEAT"});
#line 62
    await testRunner.AndAsync("I observe the following Events and Invocations of the Presence EE:", ((string)(null)), table10, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Joining and leaving channels")]
        [NUnit.Framework.CategoryAttribute("contract=presenceLeave")]
        public async System.Threading.Tasks.Task JoiningAndLeavingChannels()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=presenceLeave"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Joining and leaving channels", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 81
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 82
    await testRunner.GivenAsync("heartbeatInterval set to \'20\', timeout set to \'60\' and suppressLeaveEvents set to" +
                        " \'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 83
    await testRunner.WhenAsync("I join \'first\', \'second\', \'third\' channels with presence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 84
    await testRunner.ThenAsync("I wait for getting Presence joined events", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 85
    await testRunner.ThenAsync("I leave \'first\' and \'second\' channels with presence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 86
    await testRunner.ThenAsync("I wait \'3\' seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "name"});
                table11.AddRow(new string[] {
                            "event",
                            "JOINED"});
                table11.AddRow(new string[] {
                            "invocation",
                            "HEARTBEAT"});
                table11.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_SUCCESS"});
                table11.AddRow(new string[] {
                            "invocation",
                            "WAIT"});
                table11.AddRow(new string[] {
                            "event",
                            "LEFT"});
                table11.AddRow(new string[] {
                            "invocation",
                            "CANCEL_WAIT"});
                table11.AddRow(new string[] {
                            "invocation",
                            "LEAVE"});
                table11.AddRow(new string[] {
                            "invocation",
                            "HEARTBEAT"});
                table11.AddRow(new string[] {
                            "event",
                            "HEARTBEAT_SUCCESS"});
                table11.AddRow(new string[] {
                            "invocation",
                            "WAIT"});
#line 87
    await testRunner.AndAsync("I observe the following Events and Invocations of the Presence EE:", ((string)(null)), table11, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Joining a few channels with heartbeat interval set to 0")]
        [NUnit.Framework.CategoryAttribute("contract=presenceJoinWithHeartbeatDisabled")]
        public async System.Threading.Tasks.Task JoiningAFewChannelsWithHeartbeatIntervalSetTo0()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=presenceJoinWithHeartbeatDisabled"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Joining a few channels with heartbeat interval set to 0", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 102
    await testRunner.GivenAsync("heartbeatInterval set to \'0\', timeout set to \'60\' and suppressLeaveEvents set to " +
                        "\'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 103
    await testRunner.WhenAsync("I join \'first\', \'second\', \'third\' channels", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 104
    await testRunner.ThenAsync("I don\'t observe any Events and Invocations of the Presence EE", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
